export const hits = [
    {
        _links: {},
        recipe: {
            "uri": "http://www.edamam.com/ontologies/edamam.owl#recipe_b79327d05b8e5b838ad6cfd9576b30b6",
            "label": "Basic Turkey Gravy Recipe",
            "image":
                "https://www.edamam.com/web-img/f0c/f0c28799f982d3feb7cda573a6ae217f.jpg",
            "images": {
                "THUMBNAIL": {
                    "url": "https://www.edamam.com/web-img/f0c/f0c28799f982d3feb7cda573a6ae217f-s.jpg",
                    "width": 100,
                    "height": 100,
                },
                "SMALL": {
                    "url": "https://www.edamam.com/web-img/f0c/f0c28799f982d3feb7cda573a6ae217f-m.jpg",
                    "width": 200,
                    "height": 200,
                },
                "REGULAR": {
                    "url": "https://www.edamam.com/web-img/f0c/f0c28799f982d3feb7cda573a6ae217f.jpg",
                    "width": 300,
                    "height": 300,
                },
                "LARGE": {
                    "url": "https://www.edamam.com/web-img/f0c/f0c28799f982d3feb7cda573a6ae217f-l.jpg",
                    "width": 600,
                    "height": 600,
                },
            },
            "source": "Serious Eats",
            "ingredientLines": [
                "1/4 cup butter",
                "1/4 cup flour",
                "4 cups turkey drippings or turkey stock",
                "Kosher salt and freshly ground black pepper",
            ],
            "ingredients": [
                {
                    "text": "1/4 cup butter",
                    "quantity": 0.25,
                    "measure": "cup",
                    "food": "butter",
                    "weight": 56.75,
                    foodCategory: "string",
                    foodId: "string",
                    image: "string",
                },
                {
                    "text": "1/4 cup flour",
                    "quantity": 0.25,
                    "measure": "cup",
                    "food": "flour",
                    "weight": 31.25,
                    foodCategory: "string",
                    foodId: "string",
                    image: "string",
                },
                {
                    "text": "4 cups turkey drippings or turkey stock",
                    "quantity": 4,
                    "measure": "cup",
                    "food": "turkey stock",
                    "weight": 960,
                    foodCategory: "string",
                    foodId: "string",
                    image: "string",
                },
                {
                    "text": "Kosher salt and freshly ground black pepper",
                    "quantity": 0,
                    "measure": "null",
                    "food": "Kosher salt",
                    "weight": 6.288,
                    foodCategory: "string",
                    foodId: "string",
                    image: "string",
                },
                {
                    "text": "Kosher salt and freshly ground black pepper",
                    "quantity": 0,
                    "measure": "null",
                    "food": "black pepper",
                    "weight": 3.144,
                    foodCategory: "string",
                    foodId: "string",
                    image: "string",
                },
            ],
        },
    },

    {
        _links: {},
        recipe: {
            "uri": "http://www.edamam.com/ontologies/edamam.owl#recipe_8275bb28647abcedef0baaf2dcf34f8b",
            "label": "Basic Turkey Gravy Recipe",
            "image":
                "https://www.edamam.com/web-img/f0c/f0c28799f982d3feb7cda573a6ae217f.jpg",
            "images": {
                "THUMBNAIL": {
                    "url": "https://www.edamam.com/web-img/f0c/f0c28799f982d3feb7cda573a6ae217f-s.jpg",
                    "width": 100,
                    "height": 100,
                },
                "SMALL": {
                    "url": "https://www.edamam.com/web-img/f0c/f0c28799f982d3feb7cda573a6ae217f-m.jpg",
                    "width": 200,
                    "height": 200,
                },
                "REGULAR": {
                    "url": "https://www.edamam.com/web-img/f0c/f0c28799f982d3feb7cda573a6ae217f.jpg",
                    "width": 300,
                    "height": 300,
                },
                "LARGE": {
                    "url": "https://www.edamam.com/web-img/f0c/f0c28799f982d3feb7cda573a6ae217f-l.jpg",
                    "width": 600,
                    "height": 600,
                },
            },
            "source": "Serious Eats",
            "ingredientLines": [
                "1/4 cup butter",
                "1/4 cup flour",
                "4 cups turkey drippings or turkey stock",
                "Kosher salt and freshly ground black pepper",
            ],
            "ingredients": [
                {
                    "text": "1/4 cup butter",
                    "quantity": 0.25,
                    "measure": "cup",
                    "food": "butter",
                    "weight": 56.75,
                    foodCategory: "string",
                    foodId: "string",
                    image: "string",
                },
                {
                    "text": "1/4 cup flour",
                    "quantity": 0.25,
                    "measure": "cup",
                    "food": "flour",
                    "weight": 31.25,
                    foodCategory: "string",
                    foodId: "string",
                    image: "string",
                },
                {
                    "text": "4 cups turkey drippings or turkey stock",
                    "quantity": 4,
                    "measure": "cup",
                    "food": "turkey stock",
                    "weight": 960,
                    foodCategory: "string",
                    foodId: "string",
                    image: "string",
                },
                {
                    "text": "Kosher salt and freshly ground black pepper",
                    "quantity": 0,
                    "measure": "null",
                    "food": "Kosher salt",
                    "weight": 6.288,
                    foodCategory: "string",
                    foodId: "string",
                    image: "string",
                },
                {
                    "text": "Kosher salt and freshly ground black pepper",
                    "quantity": 0,
                    "measure": "null",
                    "food": "black pepper",
                    "weight": 3.144,
                    foodCategory: "string",
                    foodId: "string",
                    image: "string",
                },
            ],
        },
    },
];
